### ISSUE TITLE
Add dependency to internationalization library?

### ISSUE THREAD

**Issue by YetAnotherMinion** [alpacaaa/elm-date-distance#4]
I propose we change the API for translations in the library by ditching the per language module system and just use a translations dictionary such as http://package.elm-lang.org/packages/ChristophP/elm-i18next/latest/I18Next.

I dislike the per language module approach because it bloats the compiled application size. To my use case, it is more elegant to only load the translations that you are going to use, not all of them for every language.

The particular i18n library I mention above has already implemented string interpolation, so it would make it even easier to rip the existing translation strings fron date-fn (such as https://github.com/date-fns/date-fns/blob/master/src/locale/ru/_lib/formatDistance/index.js) to fill out the languages this library supports.

It appears to me that this library could be simplified and shortened dramatically by using any i18n library that operates like a `Dict String String`.

**Comment by alpacaaa** [comment]
I'm not a big fan of having a dependency on another internationalization library, I think I like the current situation better.

> I dislike the per language module approach because it bloats the compiled application size

Do you have a source for this? I assume the compiler won't include unused modules in the final bundle. Keep in mind only the `En` module is currently pulled in by default and it's fairly lightweight so it shouldn't impact too much. Also, I believe a lot of work is being put in Elm 0.19 on this front so I would at least wait for the next release of the compiler before doing any work in that direction.

> It appears to me that this library could be simplified and shortened dramatically by using any i18n library that operates like a Dict String String.

Maybe so, but our translations needs are so basic that I figured contributors would just be better off interpolating strings manually and get the job done. This is such a tiny library, I wouldn't want to complicate it too much. Would love to hear more thoughts on this.

**Comment by YetAnotherMinion** [comment]
My understanding is that elm compiler today and upcoming 0.19 lacks compile time reflection or conditional compilation. This means to me if I have an application that will be translated into 37 languages, then my understanding is that 37 duplicates of each function from this library will be compiled in.

Because *to my knowledge* the tooling is not there to make it easy for me to compile a different version of my app for each language, then the Dict String String interface is very attractive because it lets me load translation files using the infrastructure I am already using for the rest of the app.

Adopting an Dict String String interface internally would allow you to still have hardcoded `...I18n.En` ... modules for people using conditional compilation, but would also allow people using the dynamic style of translations to reuse most of the library code. I could see there being a base distance library that just does the calculations, and then two wrapper libraries on top that renders the text. Where one library would take the 1 language per module approach to server the static compiling people and the other library would take the approach of expecting a Dict String String to serve the dynamic translations people.

**Edit**: Reading the code again you already kind of do that. What I propose is that I will write a module `I18n.Dynamic` which will accept a Dict String String for those who want to dynamically provide translations.

**Comment by alpacaaa** [comment]
Thanks for the detailed explanation!

I kind of get what you're proposing. I like the idea of having a `I18n.Dynamic` module, especially if it doesn't bring in other dependencies (my guess is that locking this library to a specific internationalization library isn't a very good idea).

Feel free to stub out a tentative api for this module with the types you have in mind, or if you're down to open a pull request that would be great as well.

**Comment by alpacaaa** [comment]
Might revisit this in the future, closing for now.
