### ISSUE TITLE
Plans to upgrade to Elm 0.19?

### ISSUE THREAD

**Issue by AdrianoFerrari** [alpacaaa/elm-date-distance#6]
Hi @alpacaaa .

I've found this package very useful, thank you!
Do you intend to upgrade to 0.19?

**Comment by alpacaaa** [comment]
Hey thanks :) No plans at the moment, but I'll gladly accept PRs. I suspect updating isn't going to be too painful.

**Comment by michaeljones** [comment]
Running `elm-upgrade` highlights that `justinmimbs/elm-date-extra` hasn't been updated for Elm-0.19 and according to [this issue](https://github.com/justinmimbs/elm-date-extra/issues/9) that isn't likely to happen so a more detailed look needs to be taken into what is being used from that library and how to deal with that.

**Comment by thitemple** [comment]
So I've been slowly working on upgrading this and the main thing is that I'm using `Posix` instead of `Date` . The main issue with that is for functions such as `moreThanTwoMonths` that is converting to Months. For that I  need a `Time.Zone`, should I ask that from the user?

**Comment by michaeljones** [comment]
Thanks for looking into it. I don't know what things are going to look like in Elm 0.19, maybe it is safe to assume that users will always have the time zone handy as well. 

Alternatively you could argument that a maximum +/- 12 hour error on a reference to something being 2 months ago is acceptable so just hard coded a UTC time zone?

**Comment by thitemple** [comment]
Well, that would work for that function but what about this one https://github.com/alpacaaa/elm-date-distance/blob/0d3bc798ded923c94f6f9a83dcdf008aae28a5d6/src/Date/Distance.elm#L193 ?

It takes seconds in consideration.

**Comment by michaeljones** [comment]
I'm not sure that I have the experience with `elm/time` to make an informed answer. My uninformed answer is that the API could ask for two `Posix` types and do the comparison between those. Given that they are independent of time zones that should be fine? If you want to take into account time zones then you ask for two time zones parameters as well (one per time) and do the conversion to UTC internally and then compare them. I'm not sure if that is necessary if, say, there is good documentation of how to get two times into the same timezone or into UTC or something.

Edit: The Elm 0.18 Date type doesn't really account for time zones I don't think so using Posix values and ignoring time zones should be the same? I might be wrong in my assumption about 0.18 Dates though.

**Comment by thitemple** [comment]
So here's what I have so far for the `moreThanTwoMonths` function:

```months =
            Time.posixToMillis d1
                - Time.posixToMillis d2
                |> Time.millisToPosix
                |> Time.toMonth
```

And for the `calculateDistance`

```seconds =
            Time.posixToMillis d1
                - Time.posixToMillis d2
                |> Time.millisToPosix
                |> Time.toSecond
```

I can make the comparison without knowing the Zone but the `Time.toMonth` and `Time.toSecond` functions both take a Zone as a first argument. 

I may be wrong with my approach so please let me know, but I think we need A zone to convert the Posix into a human-readable format. And with this approach I need to either wait for a Zone as an argument or use `Time.here` that returns a `Task` and I think will make things even more complicated.

**Comment by michaeljones** [comment]
Thanks for doing all this work! It would be interesting to see the code if you have time to make a pull request, then we could talk about it more there. I'm still quite interested, though I'm still building up my understanding of all this. 

I think that your approach has a certain logic to it but I fear it might need something a bit more involved. It seems it can get quite complex. I've been googling around and found the [deprecated-time library](https://package.elm-lang.org/packages/isaacseymour/deprecated-time/latest). It has [some logic](https://github.com/isaacseymour/deprecated-time/blob/1.0.0/src/Time/Date.elm#L413-L420) to deal with differences between their `DateTime` objects. It is possible that we could use that library to help manage some of the complexity but it seems that they are not planning to keep supporting it as they have decided to split it up.

One of the libraries they reference is [ryannhg/date-format](https://package.elm-lang.org/packages/ryannhg/date-format/latest) which includes a [relative module](https://package.elm-lang.org/packages/ryannhg/date-format/latest/DateFormat-Relative) which is trying to solve the same problem as this library, kind of. It is possible that if that is a trusted library, then we could implement is library in terms of that library. This library could essentially provide the languages/translations for that one. I'm not sure if the same functionality can be achieved though. 

I hope some of this helps a little. I thought I would try to help by looking at the code myself but it is quite a complicated problem. The `date-extra` library, that this library was using in Elm 0.18, was doing quite a lot of work and replacing it with just the `elm/time` library is going to be hard and a lot of the work is already done so we might just want to choose which one to use now.

**Comment by justinmimbs** [comment]
Hello,

I've ported the following functions from `justinmimbs/elm-date-extra` to [`justinmimbs/time-extra`](https://package.elm-lang.org/packages/justinmimbs/time-extra/latest/):

- `add`, `diff`, `floor`, `ceiling`, `range`, `partsToPosix` (previously `fromParts`), `toOffset` (previously `offsetFromUtc`)

All functions now take a `Zone` before the `Posix`. The only other change is that `diff` now returns the inverse of what it used to, so to migrate usage of `diff`, just swap the two time arguments.

If you have any feedback, please feel free to open an issue on [`time-extra`](https://github.com/justinmimbs/time-extra) to discuss! Thanks!

**Comment by AdrianoFerrari** [comment]
Hi All,

I was just going to dive in and implement this, when I find that this package has been published : 
https://package.elm-lang.org/packages/sporto/time-distance/latest/

Haven't tested it yet, but is "heavily inspired" by this package, and seems to do what we need. Thanks @alpacaaa for your original work on this.

**Comment by alpacaaa** [comment]
That's great to hear! 👍

**Comment by AdrianoFerrari** [comment]
I've made a PR to try to upgrade, because the sporto package isn't as flexible as this one, and doesn't have i18n support.
